### ISSUE TITLE
Language detection with php 5.6

### ISSUE THREAD

**Issue by SvetoslavStefanov** [patrickschur/language-detection#36]
Hey,
I've been trying to do some basic operations (as described in readme file), but it simply doesn't work.
I've been using PHP 5.6 for an old project and I removed those operators, which are newer (I've error reporting to E_ALL) and it doesn't have any errors, but it returns an empty array when calling this:
`$ld->detect('Mag het een onsje meer zijn?')->close();`

Any ideas what I'm doing wrong or perhaps if there are any problems with older versions of PHP?

**Comment by patrickschur** [comment]
You should not use PHP 5.6. This version is not supported anymore! The library itself requires PHP 7.2 or higher to work.

**Comment by SvetoslavStefanov** [comment]
I know that the library doesn't support 5.6, but I couldn't rewrite my entire project because of it. So I'm asking if there is something I could do to make it work on 5.6? There aren't any errors but it doesn't return any result?

**Comment by patrickschur** [comment]
I think you didn't understand... PHP 5.6 is [no longer supported](https://www.php.net/supported-versions.php) as it is end of life since 01.01.2019. You may be exposed to unpatched security vulnerabilities.

>  There aren't any errors but it doesn't return any result?

That's odd. You could try to debug the library by setting a breakpoint in the [Language.php](https://github.com/patrickschur/language-detection/blob/b455e7f2d023af8feab4c5ac966384f8ce2058e7/src/LanguageDetection/Language.php#L96) file at line 96 and test if the `$result` variable is empty or not. If it's empty, something might be wrong in the `NgramParser` class and if it's not, then something might be wrong in the `LanguageResult` class.

Maybe this will help you to narrow down the problem.

**Comment by SvetoslavStefanov** [comment]
> I think you didn't understand... PHP 5.6 is no longer supported as it is end of life since 01.01.2019. You may be exposed to unpatched security vulnerabilities.

I'll have a talk with my project owner about this. Thank you for your advice.

> Maybe this will help you to narrow down the problem.

Yeah, it helped me actually. I found out that I was missing "resources" directory and had empty "$this->tokens" array because of that reason. After downloading the directory everything worked fine. 

Thank you for your time.
