### ISSUE TITLE
What about a third party reverse index engine?

### ISSUE THREAD

**Issue by reshadman** [patrickschur/language-detection#5]
Features of this package look really good for implementing a reverse index engine (On top of Redis+PHP or PHP itself).

Great work btw :+1:

**Comment by patrickschur** [comment]
Thanks! :) I already played with the idea using an in-memory database, but I have no idea which one I should use. I've never used Redis before. Actually, I don't want to use a package which doesn't already come with PHP. If you have the expertise to do that. Could you make a pull request?

Otherwise, did I read it correctly? You want me to write a C-Extension for PHP?

**Comment by patrickschur** [comment]
Because I do not get any answer back I will close this issue until you you write back or someone else.
